name: CI/CD

on:
  push:
    branches: [ cicd ]
  pull_request:
    branches: [ cicd ]

jobs:
  prod-check:
    if: ${{ github.ref == 'refs/heads/cicd' }}
    runs-on: windows-latest
    steps:
      - run: echo "Deploying to production server on branch $GITHUB_REF"
