name: CI/CD

on:
  push:
    branches: [ cicd ]
  pull_request:
    branches: [ cicd ]

jobs:
  prod-check:
    if: ${{ github.ref == 'refs/heads/cicd' }}
    runs-on: windows-latest
    env:
      ENV_NAME: ${{ fromJSON('{"main":"Master","cicd":"Temprory"}')[github.ref_name]}}
    steps:
      - run: echo "this is a ${{env.ENV_NAME}} branch"
